name: echo_wake
description: "Personal alarm and timer app where your own voice becomes the wake-up call."
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ^3.7.0

dependencies:
  alarm: ^5.1.1
  audioplayers: ^6.4.0
  country_flags: ^3.2.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_onboarding_slider: ^1.0.11
  intl: ^0.19.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  record: ^6.0.0
  shared_preferences: ^2.5.3
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.15

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  slang_build_runner: ^4.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#42A5A5"
  image: assets/icon.png
  android: true
  ios: true
  android_12:
    image: assets/icon.png
    icon_background_color: "#42A5A5"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/i18n/
    - assets/onb1.png
    - assets/onb2.png
    - assets/onb3.png
